name: tre
version: 0.2.2
summary: tree command, improved.
description: |
  tre is a improved version of the `tree` command.
  By default, it respects git settings for ignored content.
  It has an option to create shell alias for each listed path.
  And it has colors!

confinement: classic
base: core18

parts:
  tre:
    plugin: rust
    source: .

apps:
  tre:
    command: bin/tre
