.TH "TRE" "1" "2022-06-19" "TRE 0\&.4\&.0" "Tre Manual"

.SH NAME
tre \- tree, improved.

.SH SYNOPSIS
.B tre
[path] [options]

.SH DESCRIPTION
.sp
Display file system content in tree diagram.
.sp
Hidden files and those configured to be ignored by \fBgit\fR will be
(optionally) ignored.
.sp
With correct configuration, each displayed file can have a shell alias created
for it, which opens the file in the default editor or an otherwise specified
command.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-all\fR
Print all files and directories, including hidden ones.

.TP
\fB\-d\fR, \fB\-\-directories\fR
Only list directories in output.

.TP
\fB\-e\fR, \fB\-\-editor\fR [\fIEDITOR\fR]
Create aliases for each displayed result in /tmp/tre_aliases_$USER, and add
a number in front of file name to indicate the alias name. For example, a number
"42" means an shell alias "e42" has been created. Running "e42" will cause the
associated file or directory to be open with $EDITOR, or a command specified
along with this command.

.TP
\fB\-j\fR, \fB\-\-json\fR
Output JSON instead of tree diagram.

.TP
\fB\-l\fR, \fB\-\-limit\fR [\fIDEPTH\fR]
Limit display depth file tree output.

.TP
\fB\-s\fR, \fB\-\-simple\fR
Use normal print despite gitignore settings. '-a' has higher priority.

.TP
\fB\-E\fR, \fB\-\-exclude\fR \fIPATTERN\fR
Exclude paths matching a regex pattern. Repeatable.

.TP
\fB\-e\fR, \fB\-\-color\fR \fIWHEN\fR
When to color the output. Choose from \fIautomatic\fR, \fIalways\fR, or \fInever\fR.
\fIautomatic\fR means when printing to a terminal,
tre will include colors; otherwise it will disable colors.

.TP
\fB\-v\fR, \fB\-\-version\fR
Show version number.

.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message.

.SH REPORTING BUGS
If you notice any issue, Please file a report at
\fIhttps://github.com/dduan/tre/issues\fR

.SH AUTHOR
Daniel Duan (\fIhttps://duan.ca\fR)

