name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        action:
          - build
          - test
          - check-cargo-lock
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: make ${{ matrix.action }}

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - build
          - test
          - check-cargo-lock
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: make ${{ matrix.action }}

  Windows:
    runs-on: windows-2019
    strategy:
      matrix:
        action:
          - build
          - test
          - check-cargo-lock
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: make ${{ matrix.action }}
